/* 家电行业日报数据 · 生成于 2026-07-02 01:03 */
const TODAY_DATA = {
  "date": "2026-07-02",
  "run_time": "01:03",
  "items": [
    {
      "title": "滤网智换 清洁无忧 樱花吸油烟机SCR-Q633解锁烹饪洁净新体验",
      "url": "https://kitchen.cheaa.com/2026/0104/652094.shtml",
      "source": "中国家电网",
      "tier": "H2",
      "weight": 100,
      "category": "厨电",
      "score": 9.4,
      "angle": "厨电行业动态+选购参考",
      "title_suggest": ""
    },
    {
      "title": "625亿元！第三批“国补”已下达！",
      "url": "https://news.cheaa.com/2026/0626/656072.shtml",
      "source": "中国家电网",
      "tier": "H2",
      "weight": 100,
      "category": "综合家电",
      "score": 8.1,
      "angle": "政策解读+省钱攻略",
      "title_suggest": ""
    },
    {
      "title": "一季度洗碗机下滑7%，地方补贴与新国标能否成为“破局双翼...",
      "url": "https://news.cheaa.com/2026/0616/655748.shtml",
      "source": "中国家电网",
      "tier": "H2",
      "weight": 100,
      "category": "厨电",
      "score": 8.1,
      "angle": "政策解读+省钱攻略",
      "title_suggest": ""
    },
    {
      "title": "格力亮相国家博物馆中国制造“十四五”成就展 2026-01-05",
      "url": "https://www.gree.com/Article/view/dd55025cd3094dbeb9b97412bd45f963",
      "source": "格力",
      "tier": "H1",
      "weight": 90,
      "category": "综合家电",
      "score": 7.9,
      "angle": "综合家电行业动态+选购参考",
      "title_suggest": ""
    },
    {
      "title": "格力电器主导的IEC国际标准发布，引领全球光伏产业规范发展 2026-01-05",
      "url": "https://www.gree.com/Article/view/89fc7078f9a04da8826ae130288097ad",
      "source": "格力",
      "tier": "H1",
      "weight": 90,
      "category": "综合家电",
      "score": 7.9,
      "angle": "综合家电新品速报+选购建议",
      "title_suggest": ""
    },
    {
      "title": "2024-05-23 再跨越！格力在洛阳举办冰洗生活电器战略发布会",
      "url": "https://www.gree.com/Article/view/55e8504652f747889c18238881782a16",
      "source": "格力",
      "tier": "H1",
      "weight": 90,
      "category": "综合家电",
      "score": 7.9,
      "angle": "综合家电新品速报+选购建议",
      "title_suggest": ""
    },
    {
      "title": "2024-05-16 标准领航！格力牵头制修订的7项新标发布",
      "url": "https://www.gree.com/Article/view/05454759436c4edd85b8b60dc2300b9e",
      "source": "格力",
      "tier": "H1",
      "weight": 90,
      "category": "综合家电",
      "score": 7.9,
      "angle": "综合家电新品速报+选购建议",
      "title_suggest": ""
    },
    {
      "title": "空调怎么选不踩坑假如导购讲真话 #空调 #空调怎么选 #家电 #装修 #避坑指南",
      "url": "https://www.douyin.com/video/7616306355913198875",
      "source": "抖音@李莽（家装家电避坑版）",
      "tier": "H3",
      "weight": 80,
      "category": "空调",
      "angle": "空调选购攻略（高收藏潜力）",
      "douyin_interactions": 674490,
      "douyin_comments": 4490,
      "douyin_pub_date": "2026-03-12",
      "zpid": "7616306355913198875",
      "comment_status": "抓取中",
      "score": 7.5,
      "title_suggest": ""
    },
    {
      "title": "锐评当代恶臭年轻人家电使用频率 #装修 #装修避坑 #锐评 #从夯到拉",
      "url": "https://www.douyin.com/video/7596310912722636070",
      "source": "抖音@嘉伟室内设计",
      "tier": "H3",
      "weight": 80,
      "category": "综合家电",
      "angle": "综合家电选购攻略（高收藏潜力）",
      "douyin_interactions": 621000,
      "douyin_comments": 29000,
      "douyin_pub_date": "2026-01-17",
      "zpid": "7596310912722636070",
      "comment_status": "抓取中",
      "score": 7.5,
      "title_suggest": ""
    },
    {
      "title": "家电选择困难症，这视频你必看 #装修 #装修避坑 #家电 #家电怎么选",
      "url": "https://www.douyin.com/video/7606349782520575567",
      "source": "抖音@嘉伟室内设计",
      "tier": "H3",
      "weight": 80,
      "category": "综合家电",
      "angle": "综合家电选购攻略（高收藏潜力）",
      "douyin_interactions": 268419,
      "douyin_comments": 5419,
      "douyin_pub_date": "2026-02-20",
      "zpid": "7606349782520575567",
      "comment_status": "抓取中",
      "score": 7.5,
      "title_suggest": ""
    },
    {
      "title": "装修避坑十要十不要#装修 #装修避坑 #装修设计 #厨房装修 #装修知识",
      "url": "https://www.douyin.com/video/7619550429927558450",
      "source": "抖音@牛哥讲装修",
      "tier": "H3",
      "weight": 80,
      "category": "综合家电",
      "angle": "综合家电选购攻略（高收藏潜力）",
      "douyin_interactions": 399723,
      "douyin_comments": 1723,
      "douyin_pub_date": "2026-03-21",
      "zpid": "7619550429927558450",
      "comment_status": "已抓取",
      "score": 7.5,
      "title_suggest": ""
    },
    {
      "title": "建议：买3大家电，抓住4点“选购定律”，绝非误导，都是经验总结",
      "url": "https://www.toutiao.com/article/7656396666127270400/",
      "source": "今日头条",
      "tier": "H4",
      "weight": 75,
      "category": "综合家电",
      "score": 7.0,
      "angle": "综合家电选购攻略（高收藏潜力）",
      "title_suggest": ""
    },
    {
      "title": "最新市场测评洗衣机哪个牌子好?2026家用洗衣机选购攻略",
      "url": "https://www.toutiao.com/article/7656672684947800595/",
      "source": "今日头条",
      "tier": "H4",
      "weight": 75,
      "category": "洗衣机",
      "score": 7.0,
      "angle": "洗衣机选购攻略（高收藏潜力）",
      "title_suggest": ""
    },
    {
      "title": "扫地机器人选购指南：为小白量身定制",
      "url": "https://jd.zol.com.cn/931/9311467.html",
      "source": "中关村在线家电",
      "tier": "H2",
      "weight": 70,
      "category": "清洁电器",
      "score": 6.6,
      "angle": "清洁电器选购攻略（高收藏潜力）",
      "title_suggest": ""
    },
    {
      "title": "科沃斯地宝mini评测：小户型家庭的全能清洁搭子",
      "url": "https://jd.zol.com.cn/977/9773134.html",
      "source": "中关村在线家电",
      "tier": "H2",
      "weight": 70,
      "category": "综合家电",
      "score": 6.6,
      "angle": "综合家电行业动态+选购参考",
      "title_suggest": ""
    }
  ]
};
const ARCHIVES = [
  {
    "date": "2026-07-01",
    "run_time": "",
    "items": [
      {
        "title": "滤网智换 清洁无忧 樱花吸油烟机SCR-Q633解锁烹饪洁净新体验",
        "url": "https://kitchen.cheaa.com/2026/0104/652094.shtml",
        "source": "中国家电网",
        "tier": "H2",
        "weight": 100,
        "category": "厨电",
        "score": 9.4,
        "angle": "厨电行业动态+选购参考",
        "title_suggest": ""
      },
      {
        "title": "625亿元！第三批“国补”已下达！",
        "url": "https://news.cheaa.com/2026/0626/656072.shtml",
        "source": "中国家电网",
        "tier": "H2",
        "weight": 100,
        "category": "综合家电",
        "score": 8.1,
        "angle": "政策解读+省钱攻略",
        "title_suggest": ""
      },
      {
        "title": "一季度洗碗机下滑7%，地方补贴与新国标能否成为“破局双翼...",
        "url": "https://news.cheaa.com/2026/0616/655748.shtml",
        "source": "中国家电网",
        "tier": "H2",
        "weight": 100,
        "category": "厨电",
        "score": 8.1,
        "angle": "政策解读+省钱攻略",
        "title_suggest": ""
      },
      {
        "title": "格力亮相国家博物馆中国制造“十四五”成就展 2026-01-05",
        "url": "https://www.gree.com/Article/view/dd55025cd3094dbeb9b97412bd45f963",
        "source": "格力",
        "tier": "H1",
        "weight": 90,
        "category": "综合家电",
        "score": 7.9,
        "angle": "综合家电行业动态+选购参考",
        "title_suggest": ""
      },
      {
        "title": "格力电器主导的IEC国际标准发布，引领全球光伏产业规范发展 2026-01-05",
        "url": "https://www.gree.com/Article/view/89fc7078f9a04da8826ae130288097ad",
        "source": "格力",
        "tier": "H1",
        "weight": 90,
        "category": "综合家电",
        "score": 7.9,
        "angle": "综合家电新品速报+选购建议",
        "title_suggest": ""
      },
      {
        "title": "2024-05-23 再跨越！格力在洛阳举办冰洗生活电器战略发布会",
        "url": "https://www.gree.com/Article/view/55e8504652f747889c18238881782a16",
        "source": "格力",
        "tier": "H1",
        "weight": 90,
        "category": "综合家电",
        "score": 7.9,
        "angle": "综合家电新品速报+选购建议",
        "title_suggest": ""
      },
      {
        "title": "2024-05-16 标准领航！格力牵头制修订的7项新标发布",
        "url": "https://www.gree.com/Article/view/05454759436c4edd85b8b60dc2300b9e",
        "source": "格力",
        "tier": "H1",
        "weight": 90,
        "category": "综合家电",
        "score": 7.9,
        "angle": "综合家电新品速报+选购建议",
        "title_suggest": ""
      },
      {
        "title": "空调怎么选不踩坑假如导购讲真话 #空调 #空调怎么选 #家电 #装修 #避坑指南",
        "url": "https://www.douyin.com/video/7616306355913198875",
        "source": "抖音@李莽（家装家电避坑版）",
        "tier": "H3",
        "weight": 80,
        "category": "空调",
        "angle": "空调选购攻略（高收藏潜力）",
        "douyin_interactions": 674490,
        "zpid": "7616306355913198875",
        "comment_status": "抓取中",
        "score": 7.5,
        "title_suggest": ""
      },
      {
        "title": "锐评当代恶臭年轻人家电使用频率 #装修 #装修避坑 #锐评 #从夯到拉",
        "url": "https://www.douyin.com/video/7596310912722636070",
        "source": "抖音@嘉伟室内设计",
        "tier": "H3",
        "weight": 80,
        "category": "综合家电",
        "angle": "综合家电选购攻略（高收藏潜力）",
        "douyin_interactions": 621000,
        "zpid": "7596310912722636070",
        "comment_status": "未抓取",
        "score": 7.5,
        "title_suggest": ""
      },
      {
        "title": "装修知识，快问快答 #装修 #装修避坑 #装修设计 #装修知识",
        "url": "https://www.douyin.com/video/7614955967420207862",
        "source": "抖音@廖工爱装修",
        "tier": "H3",
        "weight": 80,
        "category": "综合家电",
        "angle": "综合家电选购攻略（高收藏潜力）",
        "douyin_interactions": 176745,
        "zpid": "7614955967420207862",
        "comment_status": "未抓取",
        "score": 7.5,
        "title_suggest": ""
      },
      {
        "title": "装修避坑十要十不要#装修 #装修避坑 #装修设计 #厨房装修 #装修知识",
        "url": "https://www.douyin.com/video/7619550429927558450",
        "source": "抖音@牛哥讲装修",
        "tier": "H3",
        "weight": 80,
        "category": "综合家电",
        "angle": "综合家电选购攻略（高收藏潜力）",
        "douyin_interactions": 399723,
        "zpid": "7619550429927558450",
        "comment_status": "已抓取",
        "score": 7.5,
        "title_suggest": ""
      },
      {
        "title": "建议：买3大家电，抓住4点“选购定律”，绝非误导，都是经验总结",
        "url": "https://www.toutiao.com/article/7656396666127270400/",
        "source": "今日头条",
        "tier": "H4",
        "weight": 75,
        "category": "综合家电",
        "score": 7.0,
        "angle": "综合家电选购攻略（高收藏潜力）",
        "title_suggest": ""
      },
      {
        "title": "最新市场测评洗衣机哪个牌子好？2026家用洗衣机选购攻略",
        "url": "https://www.toutiao.com/article/7656672684947800595/",
        "source": "今日头条",
        "tier": "H4",
        "weight": 75,
        "category": "洗衣机",
        "score": 7.0,
        "angle": "洗衣机选购攻略（高收藏潜力）",
        "title_suggest": ""
      },
      {
        "title": "_导购_|_梅雨季除湿机怎么选不踩坑？除湿机十大品牌德业给你答案_ _九月_",
        "url": "https://family.pconline.com.cn/2175/21757643.html \"梅雨季除湿机怎么选不踩坑？除湿机十大品牌德业给你答案\"",
        "source": "太平洋家电",
        "tier": "H2",
        "weight": 70,
        "category": "小家电",
        "score": 4.8,
        "angle": "小家电行业动态+选购参考",
        "title_suggest": ""
      },
      {
        "title": "_导购_|_除湿机十大品牌德业，2026梅雨季怎么选？这台P40把“变频旗舰”做到了全能_ _九月_",
        "url": "https://family.pconline.com.cn/2177/21776625.html \"除湿机十大品牌德业，2026梅雨季怎么选？这台P40把“变频旗舰”做到了全能\"",
        "source": "太平洋家电",
        "tier": "H2",
        "weight": 70,
        "category": "小家电",
        "score": 4.4,
        "angle": "小家电行业动态+选购参考",
        "title_suggest": ""
      }
    ]
  }
];
const COMMENT_INSIGHTS = null;
