/* 家电行业日报数据 · 生成于 2026-07-02 16:39 */
const TODAY_DATA = {
  "date": "2026-07-02",
  "run_time": "16:39",
  "items": [
    {
      "title": "假如导购说真话，空调这么选不踩坑#空调 #空调怎么选 #家电 #装修 #避坑指南",
      "url": "https://www.douyin.com/video/7647131913622129961",
      "source": "抖音@老张讲厨电",
      "tier": "H1",
      "weight": 90,
      "category": "空调",
      "douyin_interactions": 280804,
      "douyin_comments": 1617,
      "douyin_pub_date": "2026-06-03",
      "zpid": "7647131913622129961",
      "comment_status": "未抓取",
      "heat_score": 9,
      "score": 9.5,
      "angle": "空调选购避坑",
      "title_suggest": "假如导购说真话，空调这么选不踩坑#空调 #空调怎么选 #家电 #装修 #避坑指南",
      "category_bonus": 0.8
    },
    {
      "title": "一季度洗碗机下滑7%，地方补贴与新国标能否成为“破局双翼...",
      "url": "https://news.cheaa.com/2026/0616/655748.shtml",
      "source": "中国家电网",
      "tier": "H2",
      "weight": 100,
      "category": "厨电",
      "pub_date": "2026-06-16",
      "score": 9.5,
      "angle": "洗碗机市场趋势",
      "title_suggest": "一季度洗碗机下滑7%，地方补贴与新国标能否成为“破局双翼...",
      "category_bonus": 1.5
    },
    {
      "title": "电视怎么选不踩坑？听懂导购潜台词#电视#电视怎么选#海信小墨E5SPro#家电#装修",
      "url": "https://www.douyin.com/video/7653835407045528882",
      "source": "抖音@乐白优选家电",
      "tier": "H3",
      "weight": 85,
      "category": "电视",
      "angle": "电视选购避坑",
      "douyin_interactions": 17300,
      "douyin_comments": 348,
      "douyin_pub_date": "2026-06-22",
      "zpid": "7653835407045528882",
      "comment_status": "未抓取",
      "heat_score": 6,
      "score": 9.5,
      "title_suggest": "电视怎么选不踩坑？听懂导购潜台词#电视#电视怎么选#海信小墨E5SPro#家电#装修",
      "category_bonus": 1.5
    },
    {
      "title": "硬气男人的家电冷知识：洗衣机的隐藏用法 男人在家就得硬气！ 一次#洗衣机 #洗衣机清洗 #洗衣机用法 #家电 #家庭地位",
      "url": "https://www.douyin.com/video/7604394862280052003",
      "source": "抖音@七哥说家电",
      "tier": "H3",
      "weight": 85,
      "category": "洗衣机",
      "angle": "洗衣机隐藏用法",
      "douyin_interactions": 1781303,
      "douyin_comments": 8303,
      "douyin_pub_date": "2026-02-08",
      "zpid": "7604394862280052003",
      "comment_status": "抓取中",
      "heat_score": 9,
      "score": 9.5,
      "title_suggest": "硬气男人的家电冷知识：洗衣机的隐藏用法 男人在家就得硬气！ 一次#洗衣机 #洗衣机清洗 #洗衣机用法 #家电 #家庭地位",
      "category_bonus": 1.5
    },
    {
      "title": "问界 M6 35 分钟全网最细讲解！ 这就是鸿蒙智行新一代车型开山之作？？？#问界M6静态评测首发 #问界M6 #问界 #硬核玩家计划",
      "url": "https://www.douyin.com/video/7619378714551291179",
      "source": "抖音@李大锤同学",
      "tier": "H3",
      "weight": 80,
      "category": "综合家电",
      "angle": "综合家电新品速报+选购建议",
      "douyin_interactions": 73204,
      "douyin_comments": 4779,
      "douyin_pub_date": "2026-03-22",
      "zpid": "7619378714551291179",
      "comment_status": "已抓取",
      "heat_score": 8,
      "score": 9.5,
      "title_suggest": "问界 M6 35 分钟全网最细讲解！ 这就是鸿蒙智行新一代车型开山之作？？？#问界M6静态评测首发 #问界M6 #问界 #硬核玩家计划"
    },
    {
      "title": "当老牌企业开始搞AI节能，是不是想阉割减配...拆了看！#格力空调#格力云佳Pro柜机#立式空调#空调推荐",
      "url": "https://www.douyin.com/video/7646691670666317097",
      "source": "抖音@剁手差评哥",
      "tier": "H1",
      "weight": 90,
      "category": "空调",
      "douyin_interactions": 81141,
      "douyin_comments": 833,
      "douyin_pub_date": "2026-06-02",
      "zpid": "7646691670666317097",
      "comment_status": "未抓取",
      "heat_score": 8,
      "score": 9.5,
      "angle": "空调拆解评测",
      "title_suggest": "当老牌企业开始搞AI节能，是不是想阉割减配...拆了看！#格力空调#格力云佳Pro柜机#立式空调#空调推荐",
      "category_bonus": 0.8
    },
    {
      "title": "拆完挂机拆柜机，小米强劲风Pro柜机拆解，真让人想不到#小米空调 #小米强劲风性能旗舰#小米强劲风Pro",
      "url": "https://www.douyin.com/video/7642555475220957115",
      "source": "抖音@家电大兵",
      "tier": "H3",
      "weight": 85,
      "category": "空调",
      "angle": "空调拆解评测",
      "douyin_interactions": 28973,
      "douyin_comments": 4202,
      "douyin_pub_date": "2026-05-22",
      "zpid": "7642555475220957115",
      "comment_status": "未抓取",
      "heat_score": 6,
      "score": 9.5,
      "title_suggest": "拆完挂机拆柜机，小米强劲风Pro柜机拆解，真让人想不到#小米空调 #小米强劲风性能旗舰#小米强劲风Pro",
      "category_bonus": 0.8
    },
    {
      "title": "全铜？33.5kg外机？拆解小米强劲风pro#小米空调#小米强劲风空调#小米空调换新挑战#小米强劲风性能王空调",
      "url": "https://www.douyin.com/video/7629594157720620666",
      "source": "抖音@家电大兵",
      "tier": "H3",
      "weight": 85,
      "category": "空调",
      "angle": "空调拆解评测",
      "douyin_interactions": 82199,
      "douyin_comments": 11000,
      "douyin_pub_date": "2026-04-17",
      "zpid": "7629594157720620666",
      "comment_status": "未抓取",
      "heat_score": 8,
      "score": 9.5,
      "title_suggest": "全铜？33.5kg外机？拆解小米强劲风pro#小米空调#小米强劲风空调#小米空调换新挑战#小米强劲风性能王空调",
      "category_bonus": 0.8
    },
    {
      "title": "最新市场测评洗衣机哪个牌子好?2026家用洗衣机选购攻略",
      "url": "https://www.toutiao.com/article/7656672684947800595/",
      "source": "今日头条",
      "tier": "H4",
      "weight": 75,
      "category": "洗衣机",
      "score": 9.5,
      "angle": "洗衣机选购攻略（高收藏潜力）",
      "title_suggest": "",
      "category_bonus": 1.5
    },
    {
      "title": "评测2026年洗衣机哪个牌子好:看完这份选购指南，让你少走弯路",
      "url": "https://www.toutiao.com/article/7656989834691330602/",
      "source": "今日头条",
      "tier": "H4",
      "weight": 75,
      "category": "洗衣机",
      "score": 9.5,
      "angle": "洗衣机选购攻略（高收藏潜力）",
      "title_suggest": "",
      "category_bonus": 1.5
    },
    {
      "title": "家电安装这些坑一定要知道  搞懂安装师傅潜台词 #家电 #家电安装 #装修 #避坑指南 #装修细节",
      "url": "https://www.douyin.com/video/7634487735406923008",
      "source": "抖音@乐白优选家电",
      "tier": "H3",
      "weight": 80,
      "category": "综合家电",
      "angle": "综合家电选购攻略（高收藏潜力）",
      "douyin_interactions": 457422,
      "douyin_comments": 1192,
      "douyin_pub_date": "2026-05-01",
      "zpid": "7634487735406923008",
      "comment_status": "抓取中",
      "heat_score": 9,
      "score": 9.5,
      "title_suggest": ""
    },
    {
      "title": "评测2026年洗衣机哪个牌子好:看完这份选购指南，让你少走弯路",
      "url": "https://www.toutiao.com/article/7657685580460851766/",
      "source": "今日头条",
      "tier": "H4",
      "weight": 75,
      "category": "洗衣机",
      "score": 9.5,
      "angle": "洗衣机选购攻略（高收藏潜力）",
      "title_suggest": "",
      "category_bonus": 1.5
    },
    {
      "title": "2025中国洗碗机行业高峰论坛",
      "url": "https://www.cheaa.com/CDIS/",
      "source": "中国家电网",
      "tier": "H2",
      "weight": 100,
      "category": "厨电",
      "score": 8.5,
      "angle": "行业趋势解析",
      "title_suggest": "2025年中国洗碗机行业高峰论坛：解析未来发展方向",
      "category_bonus": 1.5
    },
    {
      "title": "_导购_|_除湿机十大品牌德业，2026梅雨季怎么选？这台P40把“变频旗舰”做到了全能_ _九月_",
      "url": "https://family.pconline.com.cn/2177/21776625.html \"除湿机十大品牌德业，2026梅雨季怎么选？这台P40把“变频旗舰”做到了全能\"",
      "source": "太平洋家电",
      "tier": "H2",
      "weight": 70,
      "category": "小家电",
      "score": 7.8,
      "angle": "除湿机选购指南",
      "title_suggest": "梅雨季除湿机选购攻略：德业P40变频旗舰解析",
      "category_bonus": 0.8
    },
    {
      "title": "_导购_|_梅雨季除湿机怎么选不踩坑？除湿机十大品牌德业给你答案_ _九月_",
      "url": "https://family.pconline.com.cn/2175/21757643.html \"梅雨季除湿机怎么选不踩坑？除湿机十大品牌德业给你答案\"",
      "source": "太平洋家电",
      "tier": "H2",
      "weight": 70,
      "category": "小家电",
      "score": 7.8,
      "angle": "除湿机选购指南",
      "title_suggest": "梅雨季除湿机选购技巧：德业品牌解读",
      "category_bonus": 0.8
    }
  ],
  "ideas": [
    {
      "title": "夏季空调选购必看：四大实用功能你了解吗？",
      "title_b": "别只会选便宜空调！这些功能可能是你夏季舒适的关键",
      "category": "空调",
      "angle": "从用户实用功能出发，介绍空调在夏季使用中的必要性，以及挑选空调时需要注意的点",
      "reason": "根据头条数据，空调类文章阅读量和评论率通常在夏季达到峰值，用户在炎热的季节更关注空调功能",
      "diff": "不同于市面上常见的空调品牌和型号对比，此篇文章专注于实用性功能介绍，提供更具指导性的信息",
      "toutiao_tip": "结合实际用户评价和使用体验，可添加用户评论和真实案例，提升文章的可信度和互动性",
      "refs": [
        4,
        6
      ],
      "difficulty": "medium",
      "tier": "IDEA"
    },
    {
      "title": "告别厨房油烟困扰：高效油烟机选购攻略",
      "title_b": "为什么你家厨房油烟多？看这篇高效油烟机选购攻略",
      "category": "油烟机/厨电",
      "angle": "针对厨房油烟问题，介绍选购油烟机的关键因素和方法，帮助用户选到合适的油烟机",
      "reason": "厨房作为夏季高发油烟区域，油烟机选购攻略具有很高的关注度",
      "diff": "在油烟机选购方面，多数文章关注性能对比，此篇更注重选购时解决用户实际问题的方法",
      "toutiao_tip": "文章可加入厨房实际案例对比，展示不同品牌和型号油烟机在油烟处理上的效果差异",
      "refs": [
        1,
        7
      ],
      "difficulty": "medium",
      "tier": "IDEA"
    },
    {
      "title": "告别节水生活，夏季必看节水洗衣机推荐",
      "title_b": "夏天洗衣机怎么节水？这些节水技巧你不能错过",
      "category": "洗衣机",
      "angle": "在夏季高温多雨时期，介绍节水洗衣机选购技巧和节水方法，帮助用户选择适合夏季的洗衣机",
      "reason": "节水在夏季尤为重要，关于洗衣机节水功能的文章具有很高的关注度",
      "diff": "不同于常规洗衣机评测，本文聚焦于节水方面的特点，提供针对夏季的选购建议",
      "toutiao_tip": "添加真实用户的用水数据对比，让用户更直观地感受到节水效果",
      "refs": [
        2,
        4
      ],
      "difficulty": "medium",
      "tier": "IDEA"
    },
    {
      "title": "夏季电视选购攻略：这些功能可能是你需要的",
      "title_b": "夏天看电视需要注意什么？电视选购攻略来啦",
      "category": "电视",
      "angle": "分析夏季看电视的特点和需求，为用户提供电视选购的建议",
      "reason": "夏季是观看电视剧和综艺的高峰期，电视选购类文章在此时期流量高",
      "diff": "在众多电视品牌和型号对比中，本文强调夏季看电视的特殊需求，提供更具针对性的建议",
      "toutiao_tip": "结合夏季看电视的特点，推荐一些具有智能功能或防暑功能的电视",
      "refs": [
        5,
        7
      ],
      "difficulty": "medium",
      "tier": "IDEA"
    },
    {
      "title": "夏季高温，热水器选购有讲究",
      "title_b": "为什么你家热水器不省电？夏季选购热水器攻略",
      "category": "热水器",
      "angle": "介绍夏季热水器选购要点和注意事项，帮助用户购买合适的热水器",
      "reason": "夏季使用热水器频率增加，热水器选购指南文章在此时期具有较高关注度",
      "diff": "多数文章关注热水器品牌和型号，本文从节能环保的角度出发，为用户提供选购建议",
      "toutiao_tip": "对比不同热水器品牌在能效比、省电等方面的数据，为用户提供直观参考",
      "refs": [
        2,
        3
      ],
      "difficulty": "medium",
      "tier": "IDEA"
    },
    {
      "title": "空调旺季来了，如何选购适合的空调安装服务？",
      "title_b": "空调安装不求人？这些安装误区你了解吗？",
      "category": "空调",
      "angle": "介绍空调安装服务的选购要点，避免用户在旺季选购服务时遇到误区",
      "reason": "空调旺季期间，空调安装服务的需求和咨询量增加，此类型文章具有很高的关注度",
      "diff": "不同于一般空调选购文章，本文关注安装服务的质量和注意事项，提供实用建议",
      "toutiao_tip": "结合安装服务的真实案例和用户评价，帮助读者了解安装服务的实际效果",
      "refs": [
        6,
        8
      ],
      "difficulty": "high",
      "tier": "IDEA"
    },
    {
      "title": "以旧换新政策助力家电升级，这5款家电必看",
      "title_b": "国补升级家电？这些家电品牌优惠多多",
      "category": "综合",
      "angle": "介绍以旧换新政策对家电市场的影响，并推荐几款在政策下具有优惠的家电产品",
      "reason": "以旧换新政策和家电市场优惠信息在夏季家电换购季关注度较高",
      "diff": "结合国家政策和市场动态，推荐具有优惠和品质保证的家电产品，为用户节省开支",
      "toutiao_tip": "添加产品价格对比和购买链接，方便用户查看和购买",
      "refs": [
        1,
        3
      ],
      "difficulty": "high",
      "tier": "IDEA"
    },
    {
      "title": "夏季家电保养攻略：这些清洁小技巧你掌握了吗？",
      "title_b": "夏天家电这么脏？这些清洁技巧让你轻松打理",
      "category": "综合",
      "angle": "介绍夏季家电保养和清洁的实用技巧，帮助用户更好地维护家电使用状态",
      "reason": "夏季天气潮湿，家电容易受到污染，清洁保养文章在此时期关注度较高",
      "diff": "区别于一般家电使用说明，本文着重于夏季的家电清洁和保养问题，提供实用性内容",
      "toutiao_tip": "加入图片教程或短视频，让用户更容易理解和使用清洁技巧",
      "refs": [
        2,
        6
      ],
      "difficulty": "medium",
      "tier": "IDEA"
    }
  ]
};
